"""extend environmental persistence model

Revision ID: 973a78b76f36
Revises: db4d59c4fde6
Create Date: 2026-09-06 05:33:34.401413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973a78b76f36'
down_revision: Union[str, Sequence[str], None] = 'db4d59c4fde6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_capabilities',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'capability')
    )
    op.create_table('agent_credentials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id'),
    sa.UniqueConstraint('key_id')
    )
    op.create_table('agent_position_history',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('timestamp', 'agent_id')
    )
    op.create_table('environment_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.JSON(), nullable=False),
    sa.Column('active_hazards', sa.JSON(), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=False),
    sa.Column('observability', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_snapshots_region_id'), 'environment_snapshots', ['region_id'], unique=False)
    op.create_index(op.f('ix_environment_snapshots_timestamp'), 'environment_snapshots', ['timestamp'], unique=False)
    op.create_table('event_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['environmental_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_evidence_event_id'), 'event_evidence', ['event_id'], unique=False)
    op.create_table('mission_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_history_mission_id'), 'mission_history', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_history_timestamp'), 'mission_history', ['timestamp'], unique=False)
    op.create_table('mission_tasks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('objective', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_tasks_agent_id'), 'mission_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_mission_tasks_mission_id'), 'mission_tasks', ['mission_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=True),
    sa.Column('hazard_type', sa.String(length=100), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['environmental_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_created_at'), 'risk_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_event_id'), 'risk_assessments', ['event_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_region_id'), 'risk_assessments', ['region_id'], unique=False)
    op.create_foreign_key(None, 'environmental_events', 'regions', ['region_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'missions', 'regions', ['region_id'], ['id'], ondelete='RESTRICT')
    op.add_column('observations', sa.Column('source_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'observations', 'regions', ['region_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'security_events', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sensors', 'regions', ['region_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'telemetry', 'sensors', ['sensor_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'telemetry', 'regions', ['region_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_constraint(None, 'telemetry', type_='foreignkey')
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.drop_constraint(None, 'security_events', type_='foreignkey')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'source_id')
    op.drop_constraint(None, 'missions', type_='foreignkey')
    op.drop_constraint(None, 'environmental_events', type_='foreignkey')
    op.drop_index(op.f('ix_risk_assessments_region_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_event_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_created_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_mission_tasks_mission_id'), table_name='mission_tasks')
    op.drop_index(op.f('ix_mission_tasks_agent_id'), table_name='mission_tasks')
    op.drop_table('mission_tasks')
    op.drop_index(op.f('ix_mission_history_timestamp'), table_name='mission_history')
    op.drop_index(op.f('ix_mission_history_mission_id'), table_name='mission_history')
    op.drop_table('mission_history')
    op.drop_index(op.f('ix_event_evidence_event_id'), table_name='event_evidence')
    op.drop_table('event_evidence')
    op.drop_index(op.f('ix_environment_snapshots_timestamp'), table_name='environment_snapshots')
    op.drop_index(op.f('ix_environment_snapshots_region_id'), table_name='environment_snapshots')
    op.drop_table('environment_snapshots')
    op.drop_table('agent_position_history')
    op.drop_table('agent_credentials')
    op.drop_table('agent_capabilities')
    # ### end Alembic commands ###
